"""Add SponsorIntent model

Revision ID: 0e0261ef5693
Revises: c1a386db8066
Create Date: 2025-05-27 10:27:55.962950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0261ef5693'
down_revision = 'c1a386db8066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orphanages_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('orphanages_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
