"""Add SponsorIntent model

Revision ID: 42e043a6b21e
Revises: 866c43357e59
Create Date: 2025-05-27 10:16:17.805254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e043a6b21e'
down_revision = '866c43357e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
