"""Add SponsorIntent model

Revision ID: 553f01257017
Revises: f817e38d2131
Create Date: 2025-05-27 08:03:38.638722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553f01257017'
down_revision = 'f817e38d2131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_name', sa.String(length=100), nullable=False),
    sa.Column('sponsor_email', sa.String(length=120), nullable=False),
    sa.Column('sponsor_phone', sa.String(length=20), nullable=True),
    sa.Column('sponsorship_amount', sa.Float(), nullable=False),
    sa.Column('sponsorship_type', sa.String(length=50), nullable=True),
    sa.Column('reason_for_sponsorship', sa.Text(), nullable=False),
    sa.Column('additional_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsor_intents')
    # ### end Alembic commands ###
