"""Add SponsorIntent model

Revision ID: 5597cd5dff0c
Revises: 42e043a6b21e
Create Date: 2025-05-27 10:17:53.448392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5597cd5dff0c'
down_revision = '42e043a6b21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.drop_column('contact_info')

    # ### end Alembic commands ###
