"""Add SponsorIntent model

Revision ID: 866c43357e59
Revises: ab080f53b5d8
Create Date: 2025-05-27 10:13:46.761957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866c43357e59'
down_revision = 'ab080f53b5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.drop_column('donation_goal')

    # ### end Alembic commands ###
