"""Add SponsorIntent model

Revision ID: ab080f53b5d8
Revises: 553f01257017
Create Date: 2025-05-27 10:07:14.977261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab080f53b5d8'
down_revision = '553f01257017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation_reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('orphanage_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('report_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('analytics_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['orphanage_id'], ['orphanages.id'], name=op.f('donation_reports_orphanage_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('donation_reports_pkey'))
    )
    # ### end Alembic commands ###
