"""Initial donar fix

Revision ID: be19b7f7e8dd
Revises: a96a0bb27067
Create Date: 2025-05-26 18:45:58.893899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be19b7f7e8dd'
down_revision = 'a96a0bb27067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.drop_constraint('orphanages_registration_number_key', type_='unique')
        batch_op.drop_constraint('orphanages_user_id_key', type_='unique')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('orphanages_user_id_key', ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint('orphanages_registration_number_key', ['registration_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
