"""Add SponsorIntent model

Revision ID: c1a386db8066
Revises: 5597cd5dff0c
Create Date: 2025-05-27 10:20:51.009430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a386db8066'
down_revision = '5597cd5dff0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('established', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('number_of_children', sa.Integer(), nullable=True))
        batch_op.alter_column('donation_goal',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orphanages', schema=None) as batch_op:
        batch_op.alter_column('donation_goal',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('number_of_children')
        batch_op.drop_column('established')

    # ### end Alembic commands ###
