"""create sponsored child model

Revision ID: f817e38d2131
Revises: b239a2308b7e
Create Date: 2025-05-27 07:59:45.481907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f817e38d2131'
down_revision = 'b239a2308b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsored_children', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('short_description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('full_content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsored_children', schema=None) as batch_op:
        batch_op.alter_column('full_content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('short_description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
